# Inspired by https://discuss.circleci.com/t/how-to-test-multiple-versions-by-triggering-jobs-with-a-shell-function/11305/15.
version: 2
jobs:
  build-golatest:
    docker:
      - image: circleci/golang
    working_directory: /go/src/github.com/dreamdata-io/analytics-go
    steps:
      - checkout
      - run: make ci
  build-go113:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/dreamdata-io/analytics-go
    steps:
      - checkout
      - run: make ci
  build-go112:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/dreamdata-io/analytics-go
    steps:
      - checkout
      - run: make ci
  build-go111:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/dreamdata-io/analytics-go
    steps:
      - checkout
      - run: make ci

workflows:
  version: 2
  build:
    jobs:
      - build-golatest
      - build-go113
      - build-go112
      - build-go111
